# Site settings
title: Douglas Ek
description: Portfolio of my projects
keywords: Music, Songs, Production
author: Douglas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
